### ISSUE TITLE
Running whiteboard with wrong backend version causes endless loop and changes to not sync

### ISSUE THREAD

**Issue by juliusknorr** [nextcloud/whiteboard#487]
We ran whiteboard with a incompatible backend version which seemed to have the following effect:

- Whiteboard content is loaded and editable but changes are not synced
- Endless loop of websocket attempts but authentication failed
<img width="1504" alt="Image" src="https://github.com/user-attachments/assets/ae4057e9-dbe0-41ed-9e9d-82197f375c6e" />

We should block opening or at least show an error and block editing

**Comment by juliusknorr** [comment]
Something I'd consider mandatory for the next release @hweihwang

**Comment by hweihwang** [comment]
Fixed at: https://github.com/nextcloud/whiteboard/pull/486/commits/9f2517527c60088f702dd2a54d70fa0a8774005e

Relevant PR: https://github.com/nextcloud/whiteboard/pull/486

Caused by mismatch jwt between PHP backend and Node backend. Fixed to have:
- No infinity loop request for new jwt token incase there's mismatched
- Do not block user save, interact with the board
- Alert when having conflicts

<img width="1063" alt="Image" src="https://github.com/user-attachments/assets/513066b5-fd8c-4e7e-a834-a15c38083838" />

**Comment by arnowelzel** [comment]
Which version will work with the current Whiteboard app in NC 31.0.5?

I have NC 31.0.5 and Whiteboard 1.0.5 and no errors at all - neither in the browser nor in Docker, but contents will still not get saved to Nextcloud.

Script to install/update the Docker container (secrets and private URLs anonymized):

```
#!/bin/sh
docker pull ghcr.io/nextcloud-releases/whiteboard:release
docker stop nextcloud-whiteboard
docker rm nextcloud-whiteboard
docker run --name "nextcloud-whiteboard" -d -p 127.0.0.1:3002:3002 --restart=always -e JWT_SECRET_KEY=XXXX -e NEXTCLOUD_URL=https://mydomain.example ghcr.io/nextcloud-releases/whiteboard:release
```

Browser console:

![Image](https://github.com/user-attachments/assets/66a6e812-94da-4a48-b636-996ec93b2296)

Docker log:

```
New socket connection: nLVQ7w1aKhXVw6_sAAAH
Sending init-room event to socket nLVQ7w1aKhXVw6_sAAAH
[2818058] Arno Welzel joined room
[2818058] Designated new syncer: Arno Welzel
[2818058] Fetched 1 sockets for room-user-change event
[2818058] Returning 1 valid users for room-user-change event
[2818058] Room now has 1 users
[SOCKET] Cleaned up socket: nLVQ7w1aKhXVw6_sAAAH: {}
[2818058] User Arno Welzel disconnecting
[2818058] Syncer disconnected (all sessions), finding new syncer
[2818058] Finding new syncer. Users in room: 0
[2818058] No users left in room, no syncer needed
[2818058] Fetched 0 sockets for room-user-change event
[2818058] Returning 0 valid users for room-user-change event
```

**Comment by arnowelzel** [comment]
Just as confirmation: the Docker image version 1.1.0 and the app 1.1.0 work now. Thank you.

**Comment by rahulkatiyar19955** [comment]
@arnowelzel  I m also facing the same issue, Can you help me with a example docker compose file that you have used.

**Comment by arnowelzel** [comment]
I am not using a compose file, just the latest image with this shell script:

```
#!/bin/sh
docker pull ghcr.io/nextcloud-releases/whiteboard:release
docker stop nextcloud-whiteboard
docker rm nextcloud-whiteboard
docker run --name "nextcloud-whiteboard" -d -p 127.0.0.1:300
2:3002 --restart=always -e JWT_SECRET_KEY=<SECRET> -e NE
XTCLOUD_URL=<NEXTCLOUD-URL> ghcr.io/nextcloud-rele
ases/whiteboard:release
```
